### ISSUE TITLE
Problem with latest version of boomerang

### ISSUE THREAD

**Issue by fuzzysb** [ashwinkm/Boomerang-app-support#1]
![image](https://cloud.githubusercontent.com/assets/16162689/13346787/ba76ab5e-dc60-11e5-9b18-2bc5e05992d1.png)

i get the error above when trying to create a new project. I have tried uninstalling and re-installing. can you provide and assistance in how to troubleshoot

**Comment by ashwinkm** [comment]
Hi,
What version of chrome you are using?
Boomerang uses Javascript Promises for asynchronous task.
You need minimum version 32 to run the app.

**Comment by ashwinkm** [comment]
If it is not the case, Please check for the error logs in console window.
First, You may need to enable the Developer Tools for packed apps.
- Type chrome://flags inside your Chrome URL.
- Search for the "Enable debugging for packed apps" setting and enable it.

Now you can access the Developer Tools by right clicking anywhere inside Boomerang and selecting "inspect element".

**Comment by blown302** [comment]
I had the same issue in Windows 8 with chrome version 49.0.2623.112 m. issue went away when I upgraded to 50.0.2661.94 m and closed all tabs start working fine.

Edit: 

Issue is happening when creating project now. It's happinging on line 8 of lovefield.min.js in the timeout. The min is hard to read.

![image](https://cloud.githubusercontent.com/assets/1878018/14925775/eb1d7b1a-0dfd-11e6-89e2-6490cdfa26c0.png)

**Comment by ashwinkm** [comment]
@blown302 Can you please post the error message from console?

**Comment by ArmanIzad** [comment]
Got same error but only when I try to create a new request after adding a SOAP project. 

The error:
workspace.js:9054 Uncaught TypeError: Cannot read property 'key' of undefined

Edit: using version 2.1.0, Chrome version: 50.0.2661.94 m

**Comment by ashwinkm** [comment]
@ArmanIzad  could please share your WSDL file for testing?

**Comment by ArmanIzad** [comment]
@ashwinkm I can mail it to you the WSDL if you provide me with your email address. Sorry not comfortable sharing it in public.

**Comment by ashwinkm** [comment]
@ArmanIzad Here is my email id boomerangclient@gmail.com. Thanks.

**Comment by ArmanIzad** [comment]
@ashwinkm Sent :)

**Comment by Tricentis-Georg-Thurner** [comment]
I get the same error as @blown302 when I try to create a new project - i can see in the console:

![image](https://cloud.githubusercontent.com/assets/3016027/15245036/905a3f9e-1904-11e6-938f-abe6a07d1841.png)

and it seems to point to the same js line:
![image](https://cloud.githubusercontent.com/assets/3016027/15245064/bd8df230-1904-11e6-9887-36baa9f95580.png)

I even re-install the extension but it didn't change anything

Note: I am running Version 50.0.2661.102 m on Windows 7

**Comment by ashwinkm** [comment]
@Tricentis-Georg-Thurner,  
I don't know what causing this error.
I am not able to regenerate this issue here.

I'll update the lovefield.js library to the latest version and publish an update on webstore.
Thanks.

**Comment by woodforda** [comment]
HI.  

I had a similar error but for different reason - it ended being that boomerang expected a soapAction to be defined and my wsdl did not define one (it's not mandatory right?)

**Error**
![image](https://cloud.githubusercontent.com/assets/1104180/15705260/cd51e93a-27ee-11e6-9bf0-42499f36e1a2.png)

**Code**
![image](https://cloud.githubusercontent.com/assets/1104180/15705296/e95e5b2c-27ee-11e6-9a6a-79d1bb156459.png)

I added a null soapAction and all loaded correctly.

**Comment by ashwinkm** [comment]
@woodforda , 
Thank you for reporting this issue. 
According to [SOAP specification](https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383527), soapAction can be empty, But soapAction attribute must be present in  the WSDL with a empty value.

But anyway I'll handle this exception in the next update.

**Comment by Tricentis-Georg-Thurner** [comment]
I am now able to use it again - the issue seems to be solved

**Comment by misotolar** [comment]
I can confirm that issue with Chromium 52 on Linux:

![captura de pantalla de 2016-08-05 18-48-13](https://cloud.githubusercontent.com/assets/2345018/17443922/91cfe29a-5b3d-11e6-83f8-8e92c3897d2d.png)

**Comment by scallin** [comment]
I just started getting the error, it worked fine last week.  Error happens trying to invoke a web service from an existing project or just trying to "Create New Project".  I tried to uninstall and reinstall -didn't fix it.. 

Boomerang V2.1.3 and Chrome Version 54.0.2840.99 m

![image](https://cloud.githubusercontent.com/assets/20932971/20319331/a2be40e4-ab3b-11e6-8595-be2b2f5c8c9b.png)

**Comment by ashwinkm** [comment]
Removed lovefield. Using dexie.js now. This should fix the issue.
Please reopen if anyone still facing this issue in latest version of Boomerang.
