### ISSUE TITLE
json can not parse unicode

### ISSUE THREAD

**Issue by zhangmazi** [ashwinkm/Boomerang-app-support#10]
for example responde of josn.
`{"code":500,"message":"\u624b\u673a\u53f7\u4e0d\u80fd\u4e3a\u7a7a","data":[]}`

"\u624b\u673a\u53f7\u4e0d\u80fd\u4e3a\u7a7a" text should be parsed to "手机号不能为空".

the words is chinese language.

ARC App of Chrome is support to pretty for unicode.

can you imporve it?

**Comment by ashwinkm** [comment]
This is because may be your response **content-type** header is not json.?

**Comment by ashwinkm** [comment]
Fixed.
