### ISSUE TITLE
XML formatting in the "Response" for SOAP seems to be lost (v2.1.2)

### ISSUE THREAD

**Issue by sincere-learner** [ashwinkm/Boomerang-app-support#11]
Hi Ashwin,

Thanks for this simple and wonderful tool. I have been using it for both REST and SOAP calls for more than 4 months now, and now prefer this over SOAP UI. 

However, after the 2.1.2 update, I note that the XML formatting in the SOAP Response seems to have an issue, and it is not properly formatted as in previous versions.

Could you please address this? Do let me know in case you need other details. 
Thank you in advance :)

**Comment by ashwinkm** [comment]
Hi,

I have not made any changes to XML formatting in the v2.1.2.
Anyway I'll look into this issue.

Could you please share your raw response XML with response headers.

**Comment by sincere-learner** [comment]
Hi Ashwin,

Thanks for the quick response. Please find the attached response XML ("Raw Response" copied from the tool). Hope this will suffice.
[SimpleInfoRs_RAW.txt](https://github.com/ashwinkm/Boomerang-app-support/files/278060/SimpleInfoRs_RAW.txt)

**Comment by sincere-learner** [comment]
Hi Ashwin,

Hope you are doing good. Do you need any other detail to analyze the cause?

**Comment by ashwinkm** [comment]
Hi,
Sorry for the delayed reply.
Currently Boomerang doesn't handle the MTOM responses which is used to return the binary data or files from the web services.

Since the response returned by the server was in binary, Boomerang couldn't format the data.
In this case app will show the response in raw text format.

I also noticed that in your response actual response data was an XML. But if you check the headers **Content-Transfer-Encoding** is set to **binary**.
If you are not returning any binary files from the server, change the message encoding to **Text/XML** on server.

**Comment by sincere-learner** [comment]
Thanks Ashwin,

I am told that the response was always being sent this way, and has not changed. Wonder how it was working in prior versions of Boomerang. 
That said, is there any way for me to downgrade the Boomerang version only in my browser? Just wanted to see if that would make things any different

**Comment by ashwinkm** [comment]
Sorry. Currently there is no way to downgrade the app. 

Just came to my mind that I did do some changes to response data handling in the v2.1.0 which would effect the XML syntax highlighting.
Can you please confirm whether this issue related to XML formatting(pretty print with indentation) or just XML syntax highlighting?

**Comment by sincere-learner** [comment]
Hi Ashwin,

Thanks for the response. Like you said, it could be possible that the issue is evident after the v2.1.0, as I do not think I used Boomerang during that release
At the moment, I am concerned about the pretty print with indentation. 
All I want is for the response to be formatted and rendered in the same way how it used to be prior to v2.1.0

**Comment by ashwinkm** [comment]
I have uploaded the old version of Boomerang on [dropbox](https://dl.dropboxusercontent.com/u/16426752/app131.ZIP). 
Please download it and load it in the Chrome browser.
Do not delete the the existing app. This version is just for testing.

If you need any quick assistance, please ping me on Google hangouts.

**Comment by sincere-learner** [comment]
Thanks Ashwin,

I do see that I am receiving formatted XML after loading this version on Chrome.
This seems to work for me like before :)

**Comment by ashwinkm** [comment]
Can you please post screenshots from both the versions?

**Comment by sincere-learner** [comment]
![image](https://cloud.githubusercontent.com/assets/19472916/15708100/e5b01f8e-27fc-11e6-957c-a88a6f9fcd0c.png)

Please let me know if this will suffice
