### ISSUE TITLE
Boomerang soapAction incorrectly modelled

### ISSUE THREAD

**Issue by marembo2008** [ashwinkm/Boomerang-app-support#13]
The wsdl provides an empty soapAction in the operation definitions:

```
    <wsdl:operation name="findReceiveMoneyRequestTransaction">
        <soap:operation soapAction="" style="document"/>
        .....
    </wsdl:operation>
```

But on the http-header: SoapAction, boomerang adds the value:

```
    SoapAction: NA
```

This messes up the soap action call on the server side, as it tries to find the action to invoked with "NA" as SoapAction value.

i can replace this ofcourse manually by specifying the empty string ""

Is is possible the http-header SoapAction is read and properly mapped?

Example:

![soapaction](https://cloud.githubusercontent.com/assets/4571361/15577945/d278bbf8-235e-11e6-9ab8-3e196b35ad88.png)

**Comment by ashwinkm** [comment]
I'll fix this issue in next update.

Thank you.
