### ISSUE TITLE
Boomerang crashes at Loading

### ISSUE THREAD

**Issue by jmlavanchy** [ashwinkm/Boomerang-app-support#14]
I have a crash when Boomerang is loading the projects.

On Windows 7, with Boomerang V 2.1.2, I get a notification balloon:
![image](https://cloud.githubusercontent.com/assets/19946274/16071218/7beff0b8-32da-11e6-84ed-0e1aec87631a.png)

It may happen that the projects have been corrupted? How can I determine?
Are there some detailed log files?

Thanks for your help

Jean-Marc Lavanchy

**Comment by ashwinkm** [comment]
Hi, Boomerang doesn't keep any logs in external files.
Reinstalling the app would fix the issue. But you may loss all the data.

You can check for error logs in Chrome console window.
Go to _chrome://inspect/#apps_  ,find Boomerang and click inspect.
