### ISSUE TITLE
Auth button mislabled

### ISSUE THREAD

**Issue by benwa** [ashwinkm/Boomerang-app-support#2]
The button for authentication is just labeled "Button"
![screen shot 2016-03-03 at 18 03 35](https://cloud.githubusercontent.com/assets/1351571/13512714/60f9a536-e16a-11e5-9056-8dca3394fa0d.png)

**Comment by ashwinkm** [comment]
This button was added for testing during the development.
Can't believe I didn't notice this before.
I will remove it in the next update.
Thank you for reporting this.
