### ISSUE TITLE
Protected WSDL returns WSDL_NOT_FOUND

### ISSUE THREAD

**Issue by e-volusian** [ashwinkm/Boomerang-app-support#20]
WSDL protected by HTTP Basic Auth always returns WSDL_NOT_FOUND which is same error returned by a dummy WSDL (such as http://www.example.com/this_is_a_fake.wsdl )

When creating a service, Boomerang says "Authentication is handle by the Chrome. Open the WSDL URL in the Chrome browser first and authenticate it."   That **was** done for this test.

Info for researching:
- Windows 10
- Chrome Version 52.0.2743.116 m (64-bit)
- **company proxy in use**

I can probably test later from a non-proxy machine to see if that works...

If it _is_ the proxy, Boomerang should at least check and return appropriate error.

**Comment by e-volusian** [comment]
Does not work, regardless of proxy

**Comment by Sthing** [comment]
I have the same issue.
After returning from my summer vacation I find that existing projects with NTLM authentication no longer works.
I get "INVALID 401" even after authenticating in a chrome tab.

**Comment by newair1** [comment]
I have the same issue. After update to 2.1.3 cant add new URL, error WSDL not found

**Comment by ashwinkm** [comment]
Hi guys, This is actually Chrome browser issue.
It looks like latest version of chrome has stopped handling the authentication for apps.

**Comment by newair1** [comment]
Is it possible to repair? How can I help?31.08.2016, 19:10, "Ashwin K" notifications@github.com:Hi guys, This is actually Chrome browser issue.
It looks like latest version of chrome has stopped handling the authentication for apps.

**Comment by acemanV** [comment]
Been a while and I still can't update wsld. 
Is there already a solution to this problem?

**Comment by chanman-dev** [comment]
while defining the web service, try this http://username:password@url - this worked for me in chrome browser.
