### ISSUE TITLE
Whoops... Unexpected Error Occurred

### ISSUE THREAD

**Issue by kolisko** [ashwinkm/Boomerang-app-support#23]
Today I have some problems to open services in boomerang. When I click on "flash service" name on left sidebar I get red error "Whoops... Unexpected Error Occurred" and nothing happens. 

Till today everything worked perfectly. I tried to restart chrome and boomerang without success.

Any idea?

<img width="1108" alt="snimek obrazovky 2016-08-26 v 13 02 23" src="https://cloud.githubusercontent.com/assets/460056/18003354/64eaa372-6b8d-11e6-8409-bb39ef0307ee.png">

boomerang version 2.1.3
chrome version: Verze 52.0.2743.116 (64-bit)
os: os x el capitan 10.11.6

**Comment by ashwinkm** [comment]
Many users have already reported this issue. But I am unable to regenerate it.

Reinstalling the app may fix the issue.

**Comment by kolisko** [comment]
I fixed it already by reinstalling and restarting everything. What about to add log info / stack trace info to the app?

**Comment by NutsDmitriy** [comment]
I got same error:
go to the environment variables and remove last coma:
{
   "key": "value",
}

**Comment by zhengyq** [comment]
this error made me crazy! any solutions?

**Comment by mohamed-badaoui** [comment]
Error reproduced also for an endpoint. 
No clues on the reason why.

**Comment by vincentpazeller** [comment]
Same... I have this error. "Funnily", some service methods are opening ok and others are generating the error... Please fix!

**Comment by ashwinkm** [comment]
@vincentpazeller Can you please try updating your service?

**Comment by vincentpazeller** [comment]
@ashwinkm I did it, same message...

**Comment by ashwinkm** [comment]
@vincentpazeller Can you please share your WSDL file?

**Comment by vincentpazeller** [comment]
I'm afraid, no because it is behind BASIC authentication and is from a customer...

But I don't think the problem is linked with the WSDL file, because the PHP Soap extension is working fine with the services I cannot use with Boomerang...

**Comment by ashwinkm** [comment]
I am not able to reproduce this issue with my WSDL files. Issue can only be duplicated with some specific WSDL files. I am aware that issue is not with the WSDL, but in the WSDL parser. I need WSDL file to reproduce and fix this issue.
It will be really helpful, If you could download and share your WSDL file.

**Comment by vincentpazeller** [comment]
[ws.wsdl.zip](https://github.com/ashwinkm/Boomerang-app-support/files/1241981/ws.wsdl.zip)

For instance, the getSessionsList method is causing problems...

**Comment by ashwinkm** [comment]
Thank you.

**Comment by ashwinkm** [comment]
I have fixed this issue. Please update your app to latest version (v3.3.6).
