### ISSUE TITLE
Only default BODY of Request found

### ISSUE THREAD

**Issue by GavinAtGitHub** [ashwinkm/Boomerang-app-support#25]
Hi,

I am using the Boomerang version 2.1.3.

I try to create a request from an SOAP action, and I am expecting to see all the necessary information (e.g. Parameters, Header, action name...).

But I only have below default request BODY

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/">
    <x:Header/>
    <x:Body/>
</x:Envelope>
```

Is there the wsdl issue that fail to provide information?

Thanks for help, and the tool is really cool!

**Comment by ashwinkm** [comment]
I am sorry. I missed this.
Please reopen if you still have this issue.
