### ISSUE TITLE
reading out from environment variables

### ISSUE THREAD

**Issue by matthiasburger** [ashwinkm/Boomerang-app-support#26]
I set up an environment variable like this:

```
{
    "id": "myidentifier"
}
```

how can I access it in my request? I tried it in different ways (like this one, I found somewhere):

```
<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wei="xxxxxxxxxxx">
    <x:Header/>
    <x:Body>
        <wei:MyMethod>
            <wei:id>{{id}}</wei:id>
        </wei:MyMethod>
    </x:Body>
</x:Envelope>
```

I want to get then:
`<wei:id>myidentifier</wei:id>`

or am I trying to use the variables wrong?

**Comment by NutsDmitriy** [comment]
Hi, you should set it with {{ and }}
Like {{myidentifier}}
It works event with urls

**Comment by matthiasburger** [comment]
oh it works... I missed selecting an environment in the dropdown.. :D just using it the first day. But it's a great tool!!
