### ISSUE TITLE
Documentation for params?

### ISSUE THREAD

**Issue by mypark** [ashwinkm/Boomerang-app-support#28]
How are params and dynamic properties set?  I couldn't find documentation for it.  For instance, in postman, you can set environment variables which you then interpolate into your request by using {keyword}

**Comment by ashwinkm** [comment]
Use double curly braces {{keyword}}.
Please find the documentation for dynamic request generation [here](https://github.com/ashwinkm/Boomerang-app-support/wiki/Script-docs).

**Comment by LGEbsco** [comment]
How to reference in payload body parameters from PARAMS tab? Suggested {{ParamName}} does nto work..

**Comment by ashwinkm** [comment]
PARAMS tab is to display the Query String parameters. I think I should rename this tab to QueryString.
You can not reference parameters from the PARAMS tab.

You can reference parameters you declared in the environment window and dynamically created parameters in the script tab.

**Comment by avalanche1** [comment]
> I think I should rename this tab to QueryString

Yeah, you definitely should.
