### ISSUE TITLE
Incorrect relative path processing (SCHEMA_NOT_FOUND)

### ISSUE THREAD

**Issue by stavell** [ashwinkm/Boomerang-app-support#34]
Hi, 
Congrats on the great app! 

I'm stuck on an issue where I have WSDL that includes XSDs by relative path. 

Here is an example: 
1. In the WSDL we have the following include: 
 - schemaLocation="./ClientService/findClient/schema.xsd"

2. The app finds this file, so far, so good with the forward relative path.

3. In this "./ClientService/findClient/schema.xsd" we have another include like this: 
-  schemaLocation="../../DataObjects/schema.xsd"

So here comes the problem. The app treats these "../../" relative to the WSDL location, not the directory of the file where they are declared (./ClientService/findClient/)

In result Boomerang is searching 2 levels behind the WSDL location, not behind the XSD location and I get SCHEMA_NOT_FOUND error.

Hope the description of the problem is good enough.

Thanks in advance!

**Comment by ashwinkm** [comment]
Fixed in v3.3.5
