### ISSUE TITLE
Add an example to set env-send request-parse response-set env-send another request which uses the env variable set in response of first request

### ISSUE THREAD

**Issue by ghost** [ashwinkm/Boomerang-app-support#42]
Hi,
Could you pls provide a example in the document.
Flow :
1. Set environment variable username, password
2. send a request Login
3. parse response and get token
4. set environment variable token
5. send another request.

I was unable to do this I could only successfully do 
boomerang.setNextRequest('operation.Request2', 1000);

`
var obj = boomerang.getEnvironment();
obj.username = "hello@world.com";
obj.password = "foo bar";
var request = boomerang.getRequest('Login.Request1');
var result = boomerang.xPathIgnoreNS(request.response.body, 'Envelope/Body/LoginResponse/Token');

boomerang.setEnvironmentVariable('token', result);
boomerang.setNextRequest('anotherOperation.Request2', 1000);

request = boomerang.getRequest();
`

**Comment by ashwinkm** [comment]
Hi,

_1. Set environment variable username, password_
_2. Send a request Login_
Environment variables like "username and password" can be set in environment window. Then select that environment in request panel.

If you want create dynamic variable, use boomerang.setEnvironmentVariable method.
Please note that dynamic variables can only be accessed in its created request context and will get destroyed immediately after request completion.  

In script tab of "login request", write below code to automatically execute the next request
`boomerang.setNextRequest('anotherOperation.Request2', 1000);`

Click send to send the login request


__3. parse response and get token_
4. set environment variable token_
Your code is correct. But you should write it in your next requests script tab. not in the login request.

In script tab of "anotherOperation.Request2"
```
var request = boomerang.getRequest('Login.Request1');
var result = boomerang.xPathIgnoreNS(request.response.body, 'Envelope/Body/LoginResponse/Token');
boomerang.setEnvironmentVariable('token', result.Token); // its result.Token not result
boomerang.setNextRequest('anotherOperation.Request3', 1000);
```

and in the payload tab you can use this variable as below
`{{token}}`

You need to repeat the token retrieval code in every request's script tab to create token variable.

**Comment by ghost** [comment]
Thank You @ashwinkm, Works like a charm..
