### ISSUE TITLE
Environment variables can not be used when operation is called from script

### ISSUE THREAD

**Issue by matthijssn** [ashwinkm/Boomerang-app-support#44]
When using the script below in an empty request:
boomerang.setEnvironmentVariable('brt_id', item.TemplateId);
    var request = boomerang.getRequest('"QueryEngine".GetTemplateResultAsDataSet."PQ - Get Dimensie"');
    console.log(request);
    boomerang.clearEnvironmentVariable('brt_id');

The variable {{brt_id}} never gets replaced by the item.TemplateId in the "PW - Get Dimensie" request.

**Comment by ashwinkm** [comment]
What is the purpose of clearing brt_id variable which was set in first line?
Try removing the last line, it should work fine.

Please refer issue #42 for more info on using dynamic environment variable.
