### ISSUE TITLE
List your Service Tab UI issue

### ISSUE THREAD

**Issue by viswagb** [ashwinkm/Boomerang-app-support#47]
with the recent update ( before it was working just fine) the List drop-down of your service is not visible

ref the attached screen
 
![image](https://user-images.githubusercontent.com/5297466/29668551-a348c7a4-88ae-11e7-8699-2d07b00149fd.png)

**Comment by ashwinkm** [comment]
Thank you for reporting this issue.
Fixed in v3.4.1.
