### ISSUE TITLE
Price Not Available

### ISSUE THREAD

**Issue by janja-janja** [ashwinkm/Boomerang-app-support#49]
<img width="1086" alt="screen shot 2017-10-05 at 4 15 40 pm" src="https://user-images.githubusercontent.com/9822841/31229166-7c8c14da-a9e8-11e7-960e-3a4cb9ba7f3f.png">

**Comment by ashwinkm** [comment]
Google payment is not available in few regions.
Try adding ?gl=US to end of the webstore URL. You will be able to download using below link.

https://chrome.google.com/webstore/detail/boomerang-soap-rest-clien/eipdnjedkpcnlmmdfdkgfpljanehloah?gl=US

**Comment by janja-janja** [comment]
Thank you @ashwinkm !
