### ISSUE TITLE
Creating a new Request freezes Boomerang

### ISSUE THREAD

**Issue by bcarideo** [ashwinkm/Boomerang-app-support#51]
When I click on "Create request" within one of the calls created by my WSDL Boomerang just freezes up.

**Comment by ashwinkm** [comment]
I am not able to reproduce this issue using my WSDL files.
Can you please share your WSDL file?

**Comment by bcarideo** [comment]
Thanks for getting back to me. The WSDL lives here:


  *   https://efm-sandbox.ecourt.com:8443/sustain/ws/soap/niem/FilingReview/?wsdl
You may need credentials to get to it, though, and I am not authorized to share those with anyone outside our organization at this time.

[cid:image002.png@01D2C26B.7A2CA0C0]

Brian Carideo

Product Manager, One Legal

(800) 938-8815 | www.onelegal.com<http://www.onelegal.com/> | Request a demo<http://www.onelegal.com/demo>


Facebook<https://www.facebook.com/OneLegalServices/> | LinkedIn<https://www.linkedin.com/company/one-legal-llc> | Twitter<https://twitter.com/onelegal> | Blog<http://www.onelegal.com/blog> | Support<http://www.onelegal.com/support/overview/>








Choose the simplest way to file. With Email to File<http://www.onelegal.com/products/email-to-file/> it’s as easy as sending us an email.
A specialist will assemble, review and submit your filing on your behalf. Learn more.<http://www.onelegal.com/products/email-to-file/>

**Comment by ashwinkm** [comment]
Thank you for sharing your WSDL file.
I am now able to reproduce this issue. 
I did some testing and found that generated request was too long. It had around 200k lines. 
Boomerang is a web based client and browser has its own limitation for the web apps. 
Boomerang was tested with upto 3k lines of request. 
Native client like soapUI should be able to generate such large size requests. But It too got hanged while generating the request.
I will try to improve the performance of Boomerang in the future version.

**Comment by bcarideo** [comment]
Thank you very much for the explanation. I really appreciate that.

[cid:image002.png@01D2C26B.7A2CA0C0]

Brian Carideo

Product Manager, One Legal

(800) 938-8815 | www.onelegal.com<http://www.onelegal.com/> | Request a demo<http://www.onelegal.com/demo>


Facebook<https://www.facebook.com/OneLegalServices/> | LinkedIn<https://www.linkedin.com/company/one-legal-llc> | Twitter<https://twitter.com/onelegal> | Blog<http://www.onelegal.com/blog> | Support<http://www.onelegal.com/support/overview/>








Choose the simplest way to file. With Email to File<http://www.onelegal.com/products/email-to-file/> it’s as easy as sending us an email.
A specialist will assemble, review and submit your filing on your behalf. Learn more.<http://www.onelegal.com/products/email-to-file/>
