### ISSUE TITLE
How to send POST method of Content-Type= application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by FMuro77** [ashwinkm/Boomerang-app-support#59]
Hello there:
So far as was not able to send request of contect-type equal to application/x-www-form-urlencoded
Is is possible in Boomerang?

Here is an example of the request:

cURL, obtener token:
curl -X “POST” “https://idp.comprobanteselectronicos.go.cr/auth/realms/rut-stag/protocol/openid-
connect/token” \
-H ‘Content-Type: application/x-www-form-urlencoded; charset=utf-8’ \
--data-urlencode “client_id=api-stag” \
--data-urlencode “username=cpj-3-101-261506@stag.comprobanteselectronicos.go.cr” \
--data-urlencode ‘password=W$/JX/AS@K);1]I;u|+6’ \
--data-urlencode “grant_type=password”

HTTPie, obtener token:
http --form POST ‘https://idp.comprobanteselectronicos.go.cr/auth/realms/rut-stag/protocol/openid-
connect/token’ \
‘Content-Type’:’application/x-www-form-urlencoded; charset=utf-8’ \
‘client_id’=’api-stag’ \
‘username’=’cpj-3-101-261506@stag.comprobanteselectronicos.go.cr’ \
‘password’=’W$/JX/AS@K);1]I;u|+6’ \
‘grant_type’=’password’

PLAIN HTTP, obtener token:
POST /auth/realms/rut-stag/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: idp.comprobanteselectronicos.go.cr
Connection: close
User-Agent: Paw/3.1.5 (Macintosh; OS X/10.13.2) GCDHTTPRequest
Content-Length: 152
grant_type=password&client_id=api-stag&username=cpj-3-101-261506%40stag.comprobanteselectronicos.
go.cr&password=W%24%2FJX%2FAS%40K%29%3B1%5DI%3Bu%7C%2B6

Kind regards.

**Comment by ashwinkm** [comment]
This is how you can make this request in Boomerang.

![image](https://user-images.githubusercontent.com/11582049/48132251-f1990f80-e2b8-11e8-992a-31685a0fdd24.png)
