### ISSUE TITLE
License can't be re-verified

### ISSUE THREAD

**Issue by josja** [ashwinkm/Boomerang-app-support#63]
I added the extension to my Chrome on my new laptop, when I verified the license (I bought last year) I chose the wrong Google account so the verification failed. 

Since I have only two Google accounts it must be the other account, but now when I click "Verify License" again, it doesn't show the verification screen anymore but it shows the "Buy" screen instead.

Is there a way to reset the flag of the failed verification?

**Comment by ashwinkm** [comment]
A quick fix is to create a new [Chrome profile](https://support.google.com/chrome/answer/2364824?) and sign in and install the app using correct Google account. You will able to verify your license again.
