### ISSUE TITLE
Projects seem to be wiped after Beta dialog or unsyncing Chrome

### ISSUE THREAD

**Issue by josja** [ashwinkm/Boomerang-app-support#68]
Not sure what exactly happened, I opened Boomerang, noticed the beta popup, clicked it away (can't wait and will try soon!) but none my services are there. 

One thing that I should mention: yesterday I unsynced my Chrome because I needed to test a different Locale/Language setting (I did not want syncing to be in the way of my localisation tests). Not sure if this is related to this issue.

(Luckily I had an export from April so only my new services are lost)

**Comment by ashwinkm** [comment]
That's weird. It sounds like your browser got reset.  Did other sites or extensions data too got wiped out?
The beta update may not have caused this. 
I also tried unsyncing my Chrome and launched the Boomerang, projects were loaded normally.
