### ISSUE TITLE
How to connect to URL that requieres cert.p12/pfx?

### ISSUE THREAD

**Issue by FMuro77** [ashwinkm/Boomerang-app-support#69]
Hello,
I was not able to test connections like this:
https://sifen-test.set.gov.py/de/ws/consultas/consulta-ruc.wsdl?wsdl
that requires user side certificates (p12/pfx).

When you have the cert installed you will be able to go into the details and test, but in Boomerang it is not possible.

![image](https://user-images.githubusercontent.com/27311684/72316541-812c1200-3664-11ea-8ed5-cc97ecaa83e1.png)

Boomerang:
![image](https://user-images.githubusercontent.com/27311684/72316595-b89abe80-3664-11ea-8533-b1cc6847da57.png)
I did develop this connection directly on .NET Core 3.0/3.1 with no problem.
Regards.

**Comment by ashwinkm** [comment]
In Boomerang, use Add Service window to import all operations from a WSDL and create a request on a operation to test your API.
