### ISSUE TITLE
configurable schema location

### ISSUE THREAD

**Issue by iwascraig** [ashwinkm/Boomerang-app-support#8]
Just tried Boomerang - It's great... however
it would be nice if the default schema location ( http://schemas.xmlsoap.org/soap/envelope/ )
could be configured, one of my servers is rejecting and I have to manually convert each request to "http://www.w3.org/2003/05/soap-envelope" if I could set this in the config for the project It would save lots of time :)

**Comment by ashwinkm** [comment]
Hi, could please share your WSDL file for testing?
_(You can remove the private information from the wsdl if there is any, just make sure it is complete.)_

**Comment by iwascraig** [comment]
here 'Tis it's from a jabber server.
[sample.txt](https://github.com/ashwinkm/Boomerang-app-support/files/183531/sample.txt)

although it looks to me like this is not a generated WSDL, so the problem may lie there not with Boomerang however it did produce working requests in SOAPUI.

**Comment by ashwinkm** [comment]
Thank you, found the issue. will be fixed in next version.

**Comment by ashwinkm** [comment]
Fixed in v1.3.1.
